services:
  backend:
    build: .
    ports:
      - "5261:80"
    depends_on:
      shard1-db:
        condition: service_healthy
      shard2-db:
        condition: service_healthy

  shard1-db:
    image: postgres:15
    container_name: shard1-db
    environment:
      POSTGRES_DB: shard1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  shard2-db:
    image: postgres:15
    container_name: shard2-db
    environment:
      POSTGRES_DB: shard2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
